export { Properties }

export interface Hotel {
    name: string
}

const Properties = [
    { id: "XX0000", name: "Economy Brand Anaheim, CA" },
    { id: "XX0001", name: "Midscale Brand Denver, CO" },
    { id: "XX0002", name: "Midscale Brand & Conference Center Chicago, IL" },
    { id: "XX0003", name: "Economy Brand Atlanta, GA" },
    { id: "XX0004", name: "Upscale Brand New York, NY" },
    { id: "XX0005", name: "Luxury Brand Seattle, WA" },
    { id: "XX0006", name: "Economy Brand Boise, ID" },
    { id: "XX0007", name: "Midscale Brand & Suites Grand Junction, CO" },
    { id: "XX0008", name: "Economy Brand Anaheim, CA" },
    { id: "XX0009", name: "Midscale Brand Denver, CO" },
    { id: "XX0010", name: "Midscale Brand & Conference Center Chicago, IL" },
    { id: "XX0011", name: "Economy Brand Atlanta, GA" },
    { id: "XX0012", name: "Upscale Brand New York, NY" },
    { id: "XX0013", name: "Luxury Brand Seattle, WA" },
    { id: "XX0014", name: "Economy Brand Boise, ID" },
    { id: "XX0015", name: "Midscale Brand & Suites Grand Junction, CO" },
    { id: "XX0016", name: "Economy Brand Anaheim, CA" },
    { id: "XX0017", name: "Midscale Brand Denver, CO" },
    { id: "XX0018", name: "Midscale Brand & Conference Center Chicago, IL" },
    { id: "XX0019", name: "Economy Brand Atlanta, GA" },
    { id: "XX0020", name: "Upscale Brand New York, NY" },
    { id: "XX0021", name: "Luxury Brand Seattle, WA" },
    { id: "XX0022", name: "Economy Brand Boise, ID" },
    { id: "XX0023", name: "Midscale Brand & Suites Grand Junction, CO" },
    { id: "XX0024", name: "Economy Brand Anaheim, CA" },
    { id: "XX0025", name: "Midscale Brand Denver, CO" },
    { id: "XX0026", name: "Midscale Brand & Conference Center Chicago, IL" },
    { id: "XX0027", name: "Economy Brand Atlanta, GA" },
    { id: "XX0028", name: "Upscale Brand New York, NY" },
    { id: "XX0029", name: "Luxury Brand Seattle, WA" },
    { id: "XX0030", name: "Economy Brand Boise, ID" },
    { id: "XX0031", name: "Midscale Brand & Suites Grand Junction, CO" },
    { id: "XX0032", name: "Economy Brand Anaheim, CA" },
    { id: "XX0033", name: "Midscale Brand Denver, CO" },
    { id: "XX0034", name: "Midscale Brand & Conference Center Chicago, IL" },
    { id: "XX0035", name: "Economy Brand Atlanta, GA" },
    { id: "XX0036", name: "Upscale Brand New York, NY" },
    { id: "XX0037", name: "Luxury Brand Seattle, WA" },
    { id: "XX0038", name: "Economy Brand Boise, ID" },
    { id: "XX0038", name: "Midscale Brand & Suites Grand Junction, CO" },
    { id: "XX0040", name: "Economy Brand Anaheim, CA" },
    { id: "XX0041", name: "Midscale Brand Denver, CO" },
    { id: "XX0042", name: "Midscale Brand & Conference Center Chicago, IL" },
    { id: "XX0043", name: "Economy Brand Atlanta, GA" },
    { id: "XX0044", name: "Upscale Brand New York, NY" },
    { id: "XX0045", name: "Luxury Brand Seattle, WA" },
    { id: "XX0046", name: "Economy Brand Boise, ID" },
    { id: "XX0047", name: "Midscale Brand & Suites Grand Junction, CO" },
]