export { Properties }

export interface Hotel {
    name: string
}

const Properties = [
    { name: "Economy Brand Anaheim, CA" },
    { name: "Midscale Brand Denver, CO" },
    { name: "Midscale Brand & Conference Center Chicago, IL" },
    { name: "Economy Brand Atlanta, GA" },
    { name: "Upscale Brand New York, NY" },
    { name: "Luxury Brand Seattle, WA" },
    { name: "Economy Brand Boise, ID" },
    { name: "Midscale Brand & Suites Grand Junction, CO" },
    { name: "Economy Brand Anaheim, CA" },
    { name: "Midscale Brand Denver, CO" },
    { name: "Midscale Brand & Conference Center Chicago, IL" },
    { name: "Economy Brand Atlanta, GA" },
    { name: "Upscale Brand New York, NY" },
    { name: "Luxury Brand Seattle, WA" },
    { name: "Economy Brand Boise, ID" },
    { name: "Midscale Brand & Suites Grand Junction, CO" },
    { name: "Economy Brand Anaheim, CA" },
    { name: "Midscale Brand Denver, CO" },
    { name: "Midscale Brand & Conference Center Chicago, IL" },
    { name: "Economy Brand Atlanta, GA" },
    { name: "Upscale Brand New York, NY" },
    { name: "Luxury Brand Seattle, WA" },
    { name: "Economy Brand Boise, ID" },
    { name: "Midscale Brand & Suites Grand Junction, CO" },
    { name: "Economy Brand Anaheim, CA" },
    { name: "Midscale Brand Denver, CO" },
    { name: "Midscale Brand & Conference Center Chicago, IL" },
    { name: "Economy Brand Atlanta, GA" },
    { name: "Upscale Brand New York, NY" },
    { name: "Luxury Brand Seattle, WA" },
    { name: "Economy Brand Boise, ID" },
    { name: "Midscale Brand & Suites Grand Junction, CO" },
    { name: "Economy Brand Anaheim, CA" },
    { name: "Midscale Brand Denver, CO" },
    { name: "Midscale Brand & Conference Center Chicago, IL" },
    { name: "Economy Brand Atlanta, GA" },
    { name: "Upscale Brand New York, NY" },
    { name: "Luxury Brand Seattle, WA" },
    { name: "Economy Brand Boise, ID" },
    { name: "Midscale Brand & Suites Grand Junction, CO" },
    { name: "Economy Brand Anaheim, CA" },
    { name: "Midscale Brand Denver, CO" },
    { name: "Midscale Brand & Conference Center Chicago, IL" },
    { name: "Economy Brand Atlanta, GA" },
    { name: "Upscale Brand New York, NY" },
    { name: "Luxury Brand Seattle, WA" },
    { name: "Economy Brand Boise, ID" },
    { name: "Midscale Brand & Suites Grand Junction, CO" },
]