export { mockUserProfiles }

const mockUserProfiles = [
    { id: 1, firstName: "Jason", lastName: "Smith", role: "Management Company", title: "Regional Manager", brandEmail: "jason.smith@brand.com", personalEmail: "jasonsmith@invalid.com", phone: 555 - 555 - 6789 },
    { id: 2, firstName: "Michael", lastName: "Doe", role: "Management Company", title: "Area Director", brandEmail: "michael.doe@brand.com", personalEmail: "mdoe@invalid.com", phone: 555 - 555 - 6789 },
    { id: 3, firstName: "Chris", lastName: "Alabaster", role: "General Manager", title: "", brandEmail: "chris.alabaster@brand.com", personalEmail: "calabaster@invalid.com", phone: 555 - 555 - 6789 },
    { id: 4, firstName: "Laura", lastName: "Williams", role: "Assistant General Manager", title: "", brandEmail: "laura.williams@brand.com", personalEmail: "laurawilliams88@invalid.com", phone: null },
    { id: 5, firstName: "Christy", lastName: "Davis", role: "Housekeeping Manager", title: "", brandEmail: "christy.davis@brand.com", personalEmail: "christydavisempress@invalid.com", phone: null },
    { id: 6, firstName: "Nick", lastName: "Johnson", role: "Hotel Employee", title: "Engineer", brandEmail: null, personalEmail: "thefixitguy@invalid.com", phone: null },
    { id: 7, firstName: "Steve", lastName: "Jones", role: "Hotel Manager", title: "Guest Service Manager", brandEmail: null, personalEmail: "prettyinpink@invalid.com", phone: null },
    { id: 1, firstName: "Jason", lastName: "Smith", role: "Management Company", title: "Regional Manager", brandEmail: "jason.smith@brand.com", personalEmail: "jasonsmith@invalid.com", phone: 555 - 555 - 6789 },
    { id: 2, firstName: "Michael", lastName: "Doe", role: "Management Company", title: "Area Director", brandEmail: "michael.doe@brand.com", personalEmail: "mdoe@invalid.com", phone: 555 - 555 - 6789 },
    { id: 3, firstName: "Chris", lastName: "Alabaster", role: "General Manager", title: "", brandEmail: "chris.alabaster@brand.com", personalEmail: "calabaster@invalid.com", phone: 555 - 555 - 6789 },
    { id: 4, firstName: "Laura", lastName: "Williams", role: "Assistant General Manager", title: "", brandEmail: "laura.williams@brand.com", personalEmail: "laurawilliams88@invalid.com", phone: null },
    { id: 5, firstName: "Christy", lastName: "Davis", role: "Housekeeping Manager", title: "", brandEmail: "christy.davis@brand.com", personalEmail: "christydavisempress@invalid.com", phone: null },
    { id: 6, firstName: "Nick", lastName: "Johnson", role: "Hotel Employee", title: "Engineer", brandEmail: null, personalEmail: "thefixitguy@invalid.com", phone: null },
    { id: 7, firstName: "Steve", lastName: "Jones", role: "Hotel Manager", title: "Guest Service Manager", brandEmail: null, personalEmail: "prettyinpink@invalid.com", phone: null },
    { id: 1, firstName: "Jason", lastName: "Smith", role: "Management Company", title: "Regional Manager", brandEmail: "jason.smith@brand.com", personalEmail: "jasonsmith@invalid.com", phone: 555 - 555 - 6789 },
    { id: 2, firstName: "Michael", lastName: "Doe", role: "Management Company", title: "Area Director", brandEmail: "michael.doe@brand.com", personalEmail: "mdoe@invalid.com", phone: 555 - 555 - 6789 },
    { id: 3, firstName: "Chris", lastName: "Alabaster", role: "General Manager", title: "", brandEmail: "chris.alabaster@brand.com", personalEmail: "calabaster@invalid.com", phone: 555 - 555 - 6789 },
    { id: 4, firstName: "Laura", lastName: "Williams", role: "Assistant General Manager", title: "", brandEmail: "laura.williams@brand.com", personalEmail: "laurawilliams88@invalid.com", phone: null },
    { id: 5, firstName: "Christy", lastName: "Davis", role: "Housekeeping Manager", title: "", brandEmail: "christy.davis@brand.com", personalEmail: "christydavisempress@invalid.com", phone: null },
    { id: 6, firstName: "Nick", lastName: "Johnson", role: "Hotel Employee", title: "Engineer", brandEmail: null, personalEmail: "thefixitguy@invalid.com", phone: null },
    { id: 7, firstName: "Steve", lastName: "Jones", role: "Hotel Manager", title: "Guest Service Manager", brandEmail: null, personalEmail: "prettyinpink@invalid.com", phone: null },
    { id: 1, firstName: "Jason", lastName: "Smith", role: "Management Company", title: "Regional Manager", brandEmail: "jason.smith@brand.com", personalEmail: "jasonsmith@invalid.com", phone: 555 - 555 - 6789 },
    { id: 2, firstName: "Michael", lastName: "Doe", role: "Management Company", title: "Area Director", brandEmail: "michael.doe@brand.com", personalEmail: "mdoe@invalid.com", phone: 555 - 555 - 6789 },
    { id: 3, firstName: "Chris", lastName: "Alabaster", role: "General Manager", title: "", brandEmail: "chris.alabaster@brand.com", personalEmail: "calabaster@invalid.com", phone: 555 - 555 - 6789 },
    { id: 4, firstName: "Laura", lastName: "Williams", role: "Assistant General Manager", title: "", brandEmail: "laura.williams@brand.com", personalEmail: "laurawilliams88@invalid.com", phone: null },
    { id: 5, firstName: "Christy", lastName: "Davis", role: "Housekeeping Manager", title: "", brandEmail: "christy.davis@brand.com", personalEmail: "christydavisempress@invalid.com", phone: null },
    { id: 6, firstName: "Nick", lastName: "Johnson", role: "Hotel Employee", title: "Engineer", brandEmail: null, personalEmail: "thefixitguy@invalid.com", phone: null },
    { id: 7, firstName: "Steve", lastName: "Jones", role: "Hotel Manager", title: "Guest Service Manager", brandEmail: null, personalEmail: "prettyinpink@invalid.com", phone: null },
    { id: 1, firstName: "Jason", lastName: "Smith", role: "Management Company", title: "Regional Manager", brandEmail: "jason.smith@brand.com", personalEmail: "jasonsmith@invalid.com", phone: 555 - 555 - 6789 },
    { id: 2, firstName: "Michael", lastName: "Doe", role: "Management Company", title: "Area Director", brandEmail: "michael.doe@brand.com", personalEmail: "mdoe@invalid.com", phone: 555 - 555 - 6789 },
    { id: 3, firstName: "Chris", lastName: "Alabaster", role: "General Manager", title: "", brandEmail: "chris.alabaster@brand.com", personalEmail: "calabaster@invalid.com", phone: 555 - 555 - 6789 },
    { id: 4, firstName: "Laura", lastName: "Williams", role: "Assistant General Manager", title: "", brandEmail: "laura.williams@brand.com", personalEmail: "laurawilliams88@invalid.com", phone: null },
    { id: 5, firstName: "Christy", lastName: "Davis", role: "Housekeeping Manager", title: "", brandEmail: "christy.davis@brand.com", personalEmail: "christydavisempress@invalid.com", phone: null },
    { id: 6, firstName: "Nick", lastName: "Johnson", role: "Hotel Employee", title: "Engineer", brandEmail: null, personalEmail: "thefixitguy@invalid.com", phone: null },
    { id: 7, firstName: "Steve", lastName: "Jones", role: "Hotel Manager", title: "Guest Service Manager", brandEmail: null, personalEmail: "prettyinpink@invalid.com", phone: null },
]